version: '3.7'
services:
  nuxt:
    tty: true
    stdin_open: true
    init: true
    build:
      context: ..
      dockerfile: Dockerfile
      target: nuxt_prod
    volumes:
      - ../:/tmp/nuxt
    working_dir: /app
    ports:
      - "3000:80"
    environment:
      NODE_ENV: development
      NUXT_HOST: 0.0.0.0
    command: ['yarn', 'start']
